version: "3.8"

services:
  wifi-iphone-backup:
    # Optional build configuration
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: zjean/wifi-iphone-backup:latest
    container_name: wifi-iphone-backup
    volumes:
      - "./bin:/app/bin"
      - "./logs:/app/logs"
      - "./data:/data"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/var/lib/lockdown:/var/lib/lockdown"
      - "/var/run:/var/run"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    network_mode: host

    privileged: true
    restart: unless-stopped
